-- init order referer info 
INSERT INTO IUNI_DA_ORDER_REFER VALUES(1, 'IUNI', '官网下单', '');
INSERT INTO IUNI_DA_ORDER_REFER VALUES(2, 'IUNIDXD', '代用户下单', '');
INSERT INTO IUNI_DA_ORDER_REFER VALUES(3, 'TAOBAO', '淘宝订单', '');
INSERT INTO IUNI_DA_ORDER_REFER VALUES(4, 'TAOBAO_PAID', '已支付订单_来源于淘宝', '');
INSERT INTO IUNI_DA_ORDER_REFER VALUES(5, 'IUNI_INSIDE', '员工内部购机', '');
COMMIT;